# Generated by Django 4.0.3 on 2022-04-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_song_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='youtube_id',
            field=models.CharField(default='', max_length=500),
        ),
    ]
