# Generated by Django 4.0.3 on 2022-04-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_song_youtube_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='youtube_id',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
